package wtf.word.core.design.themes.colors

import androidx.compose.ui.graphics.Color
import wtf.word.core.design.themes.Colors

object BritishRacingGreenColors: Colors() {

    override val light_primary = Color(0xFF004225)
    override val light_onPrimary = Color(0xFFFFFFFF)
    override val light_primaryContainer = Color(0xFF00391F)
    override val light_onPrimaryContainer = Color(0xFF002110)
    override val light_secondary = Color(0xFFA0401F)
    override val light_onSecondary = Color(0xFFFFFFFF)
    override val light_secondaryContainer = Color(0xFFFFDBD0)
    override val light_onSecondaryContainer = Color(0xFF3A0B00)
    override val light_tertiary = Color(0xFF3B6470)
    override val light_onTertiary = Color(0xFFFFFFFF)
    override val light_tertiaryContainer = Color(0xFFBFE9F8)
    override val light_onTertiaryContainer = Color(0xFF001F27)
    override val light_error = Color(0xFFBA1A1A)
    override val light_errorContainer = Color(0xFFFFDAD6)
    override val light_onError = Color(0xFFFFFFFF)
    override val light_onErrorContainer = Color(0xFF410002)
    override val light_background = Color(0xFFFBFDF8)
    override val light_onBackground = Color(0xFF191C1A)
    override val light_outline = Color(0xFF7E7667)
    override val light_inverseOnSurface = Color(0xFFF0F1EC)
    override val light_inverseSurface = Color(0xFF2E312E)
    override val light_inversePrimary = Color(0xFF78DA9F)
    override val light_surfaceTint = Color(0xFF006D40)
    override val light_outlineVariant = Color(0xFFD0C5B4)
    override val light_scrim = Color(0xFF000000)
    override val light_surface = Color(0xFFF8FAF5)
    override val light_onSurface = Color(0xFF191C1A)
    override val light_surfaceVariant = Color(0xFFECE1CF)
    override val light_onSurfaceVariant = Color(0xFF4D4639)

    override val dark_primary = Color(0xFF78DA9F)
    override val dark_onPrimary = Color(0xFF00391F)
    override val dark_primaryContainer = Color(0xFF00522F)
    override val dark_onPrimaryContainer = Color(0xFF94F7BA)
    override val dark_secondary = Color(0xFFFFB59E)
    override val dark_onSecondary = Color(0xFF5D1800)
    override val dark_secondaryContainer = Color(0xFF802909)
    override val dark_onSecondaryContainer = Color(0xFFFFDBD0)
    override val dark_tertiary = Color(0xFFA3CDDB)
    override val dark_onTertiary = Color(0xFF033641)
    override val dark_tertiaryContainer = Color(0xFF224C58)
    override val dark_onTertiaryContainer = Color(0xFFBFE9F8)
    override val dark_error = Color(0xFFFFB4AB)
    override val dark_errorContainer = Color(0xFF93000A)
    override val dark_onError = Color(0xFF690005)
    override val dark_onErrorContainer = Color(0xFFFFDAD6)
    override val dark_background = Color(0xFF191C1A)
    override val dark_onBackground = Color(0xFFE1E3DE)
    override val dark_outline = Color(0xFF999080)
    override val dark_inverseOnSurface = Color(0xFF191C1A)
    override val dark_inverseSurface = Color(0xFFE1E3DE)
    override val dark_inversePrimary = Color(0xFF006D40)
    override val dark_surfaceTint = Color(0xFF78DA9F)
    override val dark_outlineVariant = Color(0xFF4D4639)
    override val dark_scrim = Color(0xFF000000)
    override val dark_surface = Color(0xFF111412)
    override val dark_onSurface = Color(0xFFC5C7C3)
    override val dark_surfaceVariant = Color(0xFF4D4639)
    override val dark_onSurfaceVariant = Color(0xFFD0C5B4)


    override val seed = Color(0xFF004225)
}
