[versions]
android-id = "com.usmonie.word.android"
android-compileSdk = "34"
android-targetSdk = "34"
android-minSdk = "24"
android-versionCode = "21"
android-versionName = "1.4.0"

ios-versionName = "1.4.0"
ios-deploymentTarget = "17.4"
