package wtf.word.core.design.themes.colors

import androidx.compose.ui.graphics.Color
import wtf.word.core.design.themes.Colors

object DeepIndigoColors: Colors() {

    override val light_primary = Color(0xFF00416A)
    override val light_onPrimary = Color(0xFFFFFFFF)
    override val light_primaryContainer = Color(0xFF001D33)
    override val light_onPrimaryContainer = Color(0xFFD9E2FF) //Color(0xFF001D33)
    override val light_secondary = Color(0xFF526070)
    override val light_onSecondary = Color(0xFFFFFFFF)
    override val light_secondaryContainer = Color(0xFFD5E4F7)
    override val light_onSecondaryContainer = Color(0xFF0E1D2A)
    override val light_tertiary = Color(0xFF695779)
    override val light_onTertiary = Color(0xFFFFFFFF)
    override val light_tertiaryContainer = Color(0xFFEFDBFF)
    override val light_onTertiaryContainer = Color(0xFF231533)
    override val light_error = Color(0xFFBA1A1A)
    override val light_errorContainer = Color(0xFFFFDAD6)
    override val light_onError = Color(0xFFFFFFFF)
    override val light_onErrorContainer = Color(0xFF410002)
    override val light_background = Color(0xFFFFFFFF)
    override val light_onBackground = Color(0xFF1A1C1E)
    override val light_surface = Color( 0xFFFAFAFC)
    override val light_onSurface = Color(0xFF1A1C1E)
    override val light_surfaceVariant = Color(0xFFF0F0F9)
    override val light_onSurfaceVariant = Color(0xFF4D4639)
    override val light_outline = Color(0xFF72777F)
    override val light_inverseOnSurface = Color(0xFFF1F0F4)
    override val light_inverseSurface = Color(0xFF2F3033)
    override val light_inversePrimary = Color(0xFF99CBFF)
    override val light_surfaceTint = Color(0xFF00629D)
    override val light_outlineVariant = Color(0xFFC2C7CF)
    override val light_scrim = Color(0xFF000000)
    override val light_surfaceBright = Color(0xFFFDFDFD)
    override val light_surfaceDim = Color(0xFFEAEAE9)
    override val light_surfaceContainer = Color(0xFFe6e6ed)
    override val light_surfaceContainerHighest = Color(0xFFbcbcd1)
    override val light_surfaceContainerHigh = Color(0xFFccccdb)
    override val light_surfaceContainerLow = Color(0xFFE6E6E8)
    override val light_surfaceContainerLowest = Color(0xFFDADADB)

    override val dark_primary = Color(0xFF99CBFF)
    override val dark_onPrimary = Color(0xFF003354)
    override val dark_primaryContainer = Color(0xFF004A78)
    override val dark_onPrimaryContainer = Color(0xFFCFE5FF)
    override val dark_secondary = Color(0xFFB9C8DA)
    override val dark_onSecondary = Color(0xFF243240)
    override val dark_secondaryContainer = Color(0xFF3A4857)
    override val dark_onSecondaryContainer = Color(0xFFD5E4F7)
    override val dark_tertiary = Color(0xFFD4BEE6)
    override val dark_onTertiary = Color(0xFF392A49)
    override val dark_tertiaryContainer = Color(0xFF504060)
    override val dark_onTertiaryContainer = Color(0xFFEFDBFF)
    override val dark_error = Color(0xFFFFB4AB)
    override val dark_errorContainer = Color(0xFF93000A)
    override val dark_onError = Color(0xFF690005)
    override val dark_onErrorContainer = Color(0xFFFFDAD6)
    override val dark_background = Color(0xFF1A1C1E)
    override val dark_onBackground = Color(0xFFE2E2E5)
    override val dark_surface = Color(0xff30353a)
    override val dark_onSurface = Color(0xFFE2E2E5)
    override val dark_surfaceVariant = Color(0xFF42474E)
    override val dark_onSurfaceVariant = Color(0xFFC2C7CF)
    override val dark_outline = Color(0xFF8C9199)
    override val dark_inverseOnSurface = Color(0xFF1A1C1E)
    override val dark_inverseSurface = Color(0xFFE2E2E5)
    override val dark_inversePrimary = Color(0xFF00629D)
    override val dark_surfaceTint = Color(0xFF99CBFF)
    override val dark_outlineVariant = Color(0xFF42474E)
    override val dark_scrim = Color(0xFF000000)

    override val dark_surfaceBright = Color(0xFFFAFAFC)
    override val dark_surfaceDim = Color(0xFFFAFAFC)
    override val dark_surfaceContainer = Color(0xFF373e45)
    override val dark_surfaceContainerHighest = Color(0xFF68727a)
    override val dark_surfaceContainerHigh = Color(0xFF535c63)
    override val dark_surfaceContainerLow = Color(0xFF323a40)
    override val dark_surfaceContainerLowest = Color(0xFF262d33)

    override val seed = Color(0xFF00416A)

}