package com.usmonie.core.kit.design.themes.colors

import androidx.compose.ui.graphics.Color
import com.usmonie.core.kit.design.themes.Colors

@Suppress("MagicNumber")
object RichMaroonColors : Colors() {
    override val light_primary = Color(0xFF800000)
    override val light_onPrimary = Color(0xFFFFFFFF)
    override val light_primaryContainer = Color(0xFF410000)
    override val light_onPrimaryContainer = light_onPrimary // Color(0xFF410000)
    override val light_secondary = Color(0xFF775651)
    override val light_onSecondary = Color(0xFFFFFFFF)
    override val light_secondaryContainer = Color(0xFFFFDAD4)
    override val light_onSecondaryContainer = Color(0xFF2C1512)
    override val light_tertiary = Color(0xFF705C2E)
    override val light_onTertiary = Color(0xFFFFFFFF)
    override val light_tertiaryContainer = Color(0xFFFBDFA6)
    override val light_onTertiaryContainer = Color(0xFF251A00)
    override val light_error = Color(0xFFBA1A1A)
    override val light_errorContainer = Color(0xFFFFDAD6)
    override val light_onError = Color(0xFFFFFFFF)
    override val light_onErrorContainer = Color(0xFF410002)
    override val light_background = Color(0xFFFFFBFF)
    override val light_onBackground = Color(0xFF201A19)
    override val light_surface = Color(0xfff5ecf5)
    override val light_onSurface = Color(0xFF201A19)
    override val light_surfaceVariant = Color(0xFFFDF2F9)
    override val light_onSurfaceVariant = Color(0xFF6B4C6B)
    override val light_outline = Color(0xFF857370)
    override val light_inverseOnSurface = Color(0xFFFBEEEC)
    override val light_inverseSurface = Color(0xFF362F2E)
    override val light_inversePrimary = Color(0xFFFFB4A8)
    override val light_surfaceTint = Color(0xFFB22B1D)
    override val light_outlineVariant = Color(0xFFD8C2BE)
    override val light_scrim = Color(0xFF000000)

    override val light_surfaceBright = Color(0xFFFEF9FE)
    override val light_surfaceDim = Color(0xFFEDE4ED)
    override val light_surfaceContainer = Color(0xFFebe1eb)
    override val light_surfaceContainerHighest = Color(0xFFe6d8e6)
    override val light_surfaceContainerHigh = Color(0xFFCDA2CD)
    override val light_surfaceContainerLow = Color(0xFFE6CBE6)
    override val light_surfaceContainerLowest = Color(0xFF5ECF5)

    override val dark_primary = Color(0xFFFFB4A8)
    override val dark_onPrimary = Color(0xFF690000)
    override val dark_primaryContainer = Color(0xFF8F0F07)
    override val dark_onPrimaryContainer = Color(0xFFFFDAD4)
    override val dark_secondary = Color(0xFFE7BDB6)
    override val dark_onSecondary = Color(0xFF442925)
    override val dark_secondaryContainer = Color(0xFF5D3F3B)
    override val dark_onSecondaryContainer = Color(0xFFFFDAD4)
    override val dark_tertiary = Color(0xFFDEC48C)
    override val dark_onTertiary = Color(0xFF3E2E04)
    override val dark_tertiaryContainer = Color(0xFF564419)
    override val dark_onTertiaryContainer = Color(0xFFFBDFA6)
    override val dark_error = Color(0xFFFFB4AB)
    override val dark_errorContainer = Color(0xFF93000A)
    override val dark_onError = Color(0xFF690005)
    override val dark_onErrorContainer = Color(0xFFFFDAD6)
    override val dark_background = Color(0xFF201A19)
    override val dark_onBackground = Color(0xFFEDE0DD)
    override val dark_surface = Color(0xff3f3433)
    override val dark_onSurface = Color(0xFFEDE0DD)
    override val dark_surfaceVariant = Color(0xFF534341)
    override val dark_onSurfaceVariant = Color(0xFFD8C2BE)
    override val dark_outline = Color(0xFFA08C89)
    override val dark_inverseOnSurface = Color(0xFF201A19)
    override val dark_inverseSurface = Color(0xFFEDE0DD)
    override val dark_inversePrimary = Color(0xFFB22B1D)
    override val dark_surfaceTint = Color(0xFFFFB4A8)
    override val dark_outlineVariant = Color(0xFF534341)
    override val dark_scrim = Color(0xFF000000)

    override val dark_surfaceBright = Color(0xff3f3433)
    override val dark_surfaceDim = Color(0xff3f3433)
    override val dark_surfaceContainer = Color(0xFF594d4c)
    override val dark_surfaceContainerHighest = Color(0xFF877674)
    override val dark_surfaceContainerHigh = Color(0xFF70615f)
    override val dark_surfaceContainerLow = Color(0xFFE6E6E8)
    override val dark_surfaceContainerLowest = Color(0xFFDADADB)

    override val seed = Color(0xFF800000)
}
